config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'explore', to: 'pages#explore'
  get 'places', to: 'pages#places'
  resources :posts, :trips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :trip
  has_one_attached :cover_photo
  has_many_attached :photos
  has_rich_text :entry

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :trips
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :country])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo, :country])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :explore ]

  def home
  end

  def explore
    if params[:query].present?
      @posts = Post.where("address ILIKE ?", "%#{params[:query]}%")
    else
      @posts = Post.all
    end
    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window: render_to_string(partial: "info_window", locals: {post: post})
      }
    end
  end

  def places
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      my_posts = Post.where(user_id: current_user.id)
      @posts = my_posts.where("address ILIKE ?", "%#{params[:query]}%")
    else
      @posts = Post.all.where(user_id: current_user.id)
    end
    @markers = @posts.geocoded.map do |post|
      {
        lat: post.latitude,
        lng: post.longitude,
        info_window: render_to_string(partial: "info_window", locals: {post: post})
      }
    end
  end

  def show
  end

  def new
    @post = Post.new
    @trip = Trip.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path, status: :see_other
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:date, :trip_id, :entry, :address, :highlight, :travel_tips, :cover_photo, photos: [])
  end

  def trip_params
    params.require(:trip).permit(:name, :photo)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = Trip.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @trip.update(trip_params)
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip.destroy
    redirect_to trips_path, status: :see_other
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelJournal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

    <%= yield %>
  </body>
  <%= render "shared/footer" %>
</html>

app/views/pages/_info_window.html.erb
<% country = ISO3166::Country.new(post.user.country) %>
<div class="info-window">
  <h5 class="card-title py-3"><%= post.address.chomp[/^([^,])+/] %></h5>
  <p class="card-text"><strong>Highlight:</strong> <%= post.highlight %></p>
  <p class="card-text"><strong>Travel tips:</strong> <%= post.travel_tips %></p>
  <p class="small"><span class="highlight">Logged by <strong><%= post.user.first_name %> <%= post.user.last_name.chr %></strong> (<%= country.emoji_flag %>) in <%= post.date.strftime("%B %Y") %></span></p>
</div>

app/views/pages/explore.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12 col-lg-6 explore-page">
      <div class="container search-bar-bg">
        <%# <div class="search-box"> %>
          <%= form_with url: explore_path, method: :get, class: "search-box" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "search-input",
              placeholder: "Search for a city, country or landmark"
            %>
            <%= submit_tag "🔍", class: "search-button" %>
          <% end %>
        <%# </div> %>
      </div>
      <div class="container pb-3">
        <div class="row">
          <% @posts.each do | post | %>
            <% country = ISO3166::Country.new(post.user.country) %>
              <div class="col-12 col-lg-6 g-3">
                <div class="card round-body">
                  <%= cl_image_tag post.cover_photo.key, class:"card-img-top round-top" %>
                  <div class="card-body">
                    <h5 class="card-title fw-bold py-2"><%= post.address %></h5>
                    <h6 class="small fw-bold">Highlight:</h6>
                    <p class="card-text"><%= post.highlight %></p>
                    <h6 class="small fw-bold">Travel tips:</h6>
                    <p class="card-text"><%= post.travel_tips %></p>
                    <p class="small"><span class="highlight">Logged by <strong><%= post.user.first_name %> <%= post.user.last_name.chr %></strong> (<%= country.emoji_flag %>) in <%= post.date.strftime("%B %Y") %></span></p>
                  </div>
                </div>

              </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6 p-0">
      <div class="maps"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-header d-flex justify-content-center align-items-center">
  <div class="container col-xxl-10 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-1 py-5">
      <div class="col-10 col-sm-8 col-lg-5">
        <%# <img src="bootstrap-themes.png" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy"> %>
      </div>
      <div class="col-lg-7 pt-3">
        <h1 class="display-3 fw-bold lh-sm mb-3 text-white">A beautiful online travel journal for every traveller.</h1>
        <h5 class="lead pb-3 fw-bold text-dark"><span class="home-highlight">Never lose a travel memory again</span></h5>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-3">
          <% if user_signed_in? %>
            <%= link_to "Create post", new_post_path, class: "btn btn-primary px-4 btn-lg me-md-2 home-btn" %>
            <%= link_to "My posts", posts_path, class: "btn btn-outline-light btn-lg px-4 fw-bold" %>
          <% else %>
            <%= link_to "Create account", new_user_registration_path, class: "btn btn-primary px-4 btn-lg me-md-2 home-btn" %>
            <%= link_to "Explore", explore_path, class: "btn btn-outline-light btn-lg px-4 fw-bold" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container py-5">
  <div class="row py-3 pb-5 justify-content-center">
    <div class="col-sm-6">
      <h2 class="text-center fw-bold">Take your travel experiences with you everywhere 🌎</h2>
    </div>
  </div>
  <div class="row text-center g-5 justify-content-center">
    <div class="col-sm-8 col-lg-4">
      <h4 class="fw-bold pb-3"><span class="highlight">Create a trip ✈️</span></h4>
      <p>Europe Trip 2021 🏰</p>
      <p>Honeymoon in Korea 🏯</p>
      <p>Journey down the Amazon River ⛴</p>
      <p>A trip is the foundation of every travellers journey. It is a collection of small, daily adventures that lead us outside of our comfort zones and into the unknown.</p>
      <p>Whether by plane, train or automobile, a few days or a few years - the trip is what encompasses every experience.
    </div>
    <div class="col-sm-8 col-lg-4">
      <h4 class="fw-bold pb-3"><span class="highlight">Write a post ✏️</span></h4>
      <p>Travel journaling is unique because it is is one of the few things that isn't done for anyone else - it is just for you.</p>
      <p>If you want to share your travel pics with friends and get tonnes of likes there are other sites for that - this is about cherishing your personal experiences through words.</p>
      <p>Every day of your trip, take 5 minutes to create a post - tagging your location, uploading one photo (Yes - just one) and journaling about your adventures.</p>
    </div>
    <div class="col-sm-8 col-lg-4">
      <h4 class="fw-bold pb-3"><span class="highlight">Share a travel hack 🤝</span></h4>
      <p>Help other travellers in the community by sharing the highlight of your day and one valuable tip that you wish you had known ahead of time.</p>
      <p>This then gets shared on our <%= link_to "explore page", explore_path, target: "_blank" %>, where travellers can search for city, country or attraction.</p>
      <p>Best of all, your memories and safe and secure - never to be lost again. You'll be able to share them with your grandkids in 30 years and they will laugh at the fact that you used to get on airplanes and visit places in-person.</p>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(post) do |f| %>
  <div class="py-3 fw-bold">
    <%= f.association :trip, :collection => current_user.trips,
      as: :radio_buttons,
      input_html: { class: "tag-selector" },
      item_wrapper_class: 'tag-item',
      label: '✈️ What trip is this?' %>
  </div>
  <div class="row">
    <div class="py-3 fw-bold col-12 col-sm-6">
      <%= f.input :date, min: Date.today, html5: true, label: "📅 Date:" %>
    </div>
    <div class="py-3 fw-bold col-12 col-sm-6">
      <%= f.input :address, label: '📍 Location:',
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}},
      placeholder: "You can search by country, city, zipcode or even a specific address"
      %>
    </div>
  </div>
  <div class="py-3 fw-bold">
    <%= f.input :cover_photo, as: :file, label: '🌃 Please select a cover photo for this post:',
    hint: "(Keep in mind this photo may be seen by other travellers)",
    input_html: { class: "mb-2" } %>
  </div>
  <div class="py-3">
  <p class="fw-bold">📝 Journal entry:</p>
    <%= f.rich_text_area :entry, label: '📝 Journal entry:', input_html: { class: 'form-style' } %>
  </div>
  <div class="last-questions">
    <p class="fw-bold">These last 2 questions help other travellers find great places to visit. </p>
    <div class=" fw-bold">
      <%= f.input :highlight, label: '🎉 The highlight of your day:' %>
    </div>
    <div class=" fw-bold">
      <%= f.input :travel_tips, label: '🙌 Tips for future travellers that may explore here:',
      hint: "Share anything you think could be valuable - a great place to eat, the best ways to get into busy museums etc.",
      input_html: { class: "mb-2" } %>
    </div>
  </div>

  <%= f.submit "Post it", :class => "submit-button" %>
<% end %>

app/views/posts/_info_window.html.erb
<div class="info-window">
  <h2 class="py-3"><span class="highlight"><%= post.address.chomp[/^([^,])+/] %></span></h2>
  <p class="fw-bold"><%= post.date.strftime("%e %b %Y") %></p>
  <%= link_to "View post", post_path(post) %>
</div>

app/views/posts/_trip_form.html.erb
<%= simple_form_for(trip) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="container py-5">
  <h1 class="text-center">Edit your post:</h1>
  <%= render "form", post: @post %>
</div>

app/views/posts/index.html.erb
<% if current_user.posts.present? %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-lg-6 index-page">
        <div class="container">
          <%= form_with url: posts_path, method: :get, class: "search-box" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "search-input",
              placeholder: "Search your posts"
            %>
            <%= submit_tag "🔍", class: "search-button" %>
          <% end %>
          <div class="row">
            <% @posts.sort_by(&:date).reverse.each do | post | %>
                <div class="col-12 col-lg-6 g-3">
                  <%= link_to post_path(post), class: "card-cat-link" do %>
                  <div class="card mb-3 border-0 round-body ">
                    <%= cl_image_tag post.cover_photo.key, class:"card-img-top round-top" %>
                    <div class="card-body text-center">
                      <p class="card-text small fw-bold text-black"><%= post.date.strftime("%e %b %Y") %></p>
                      <h3 class="card-title pb-1 fw-bold text-black"><span class="highlight"><%= post.address.chomp[/^([^,])+/] %></span></h3>
                    </div>
                  </div>
                  <% end %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-6 p-0">
        <div class="maps"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
  </div>
<% else %>
<div class="container py-5 my-3">
  <h2 class="text-center fw-bold py-5"><%= link_to "Go ahead, write your first post 💪", new_post_path, class: "text-decoration-none" %></h2>
</div>
<% end %>

app/views/posts/new.html.erb
<div class="container py-5">
  <h1 class="text-center fw-bold">Create a post:</h1>
  <% if current_user.trips.present? %>
    <%= render "form", post: @post %>
  <% else %>
    <h4 class="text-center fw-bold py-5"><%= link_to "Before you write your first post, let's create a trip", new_trip_path %></h4>
  <% end %>
</div>

app/views/posts/show.html.erb
<% if @post.user == current_user %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-6">
        <div class="container py-5">
          <p class="fst-italic text-center small">Posted on <%= @post.date.strftime("%b %d %Y") %></p>
          <h2 class="fw-bold text-center"><%= @post.address %></h2>
          <h6 class="text-center pt-1">Part of <%= link_to @post.trip.name, trip_path(@post.trip) %></h6>
          <%= cl_image_tag @post.cover_photo.key, class: "img-fluid py-3" %>
          <p><%= @post.entry %></p>
            <div class="d-flex justify-content-between pt-3">
              <div class="d-inline-block">
                <p><%= link_to "<< Back to all posts", posts_path, class: "highlight text-decoration-none text-black" %></p>
              </div>
              <div class="d-inline-block">
                <div class="d-inline-block">
                  <%= link_to edit_post_path, class: "text-decoration-none text-black" do %>
                    ✏️
                  <% end %>
                </div>
                <div class="d-inline-block">
                  <%= link_to @post,class: "text-decoration-none text-black", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                    🗑
                  <% end %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="explore-page">
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-6">
          <div class="show-secret">
            <h2 class="text-center">Other traveller's posts are private 🤫</h2>
            <p><%= link_to "Browse your own", posts_path %> or <%= link_to "create a new one", new_post_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="w-100 py-4 flex-shrink-0">
  <div class="container px-4">
    <div class="row">
      <div class="col text-center">
        <%= link_to root_path do %>
          <%= image_tag "navigation.png", class: "footer-logo" %>
        <% end %>
        <p class="text-white fw-bold pb-3"><span class="highlight">Never lose a travel memory again.</span></p>
        <div class="row justify-content-center pb-3">
          <div class="col-sm-8 col-lg-4">
            <div class="row justify-content-between">
              <div class="col-12 col-md-3">
                <%= link_to "Home", root_path %>
              </div>
              <div class="col-12 col-md-3">
                <%= link_to "Explore", explore_path %>
              </div>
              <div class="col-12 col-md-3">
                <% if user_signed_in? %>
                  <%= link_to "My posts", posts_path %>
                <% else %>
                  <%= link_to "Get started", new_user_registration_path %>
                <% end %>
              </div>
              <div class="col-12 col-md-3">
                <% if user_signed_in? %>
                  <%= link_to "Create post", new_post_path %>
                <% else %>
                  <%= link_to "Login", new_user_session_path %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <%# <p class="small text-muted"><a href="#">Home</a> · <a href="#">About</a> · <a href="#">Get started</a> · <a href="#">FAQ</a></p> %>
        <p class="small text-muted">
          Made with <i class="fas fa-heart"></i> in Honolulu, Hawaii
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon p-3">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "navigation.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <%= link_to "Explore", explore_path, class: "nav-link pe-5" %>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My posts", posts_path, class: "nav-link pe-5" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create post", new_post_path, class: "nav-link pe-5" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag(current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" })%>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My trips", trips_path, class: "dropdown-item" %>
              <%= link_to "Where I've been", places_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <%# <li class="nav-item"> %>
            <%= link_to "Login", new_user_session_path, class: "nav-link pe-5" %>
            <%= link_to "Create account", new_user_registration_path, class: "btn btn-primary nav-btn" %>
          <%# </li> %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/trips/_form.html.erb
<%= simple_form_for(trip) do |f| %>
  <%= f.input :name, label: "Give your trip a name:", placeholder: "Europe Trip 2022, Korea Trip 2021 etc" %>
  <%= f.input :photo, as: :file, label: "Choose a cover photo for your trip ✈️:" %>
  <%= f.submit "create", class: "btn btn-primary home-btn" %>
<% end %>

app/views/trips/edit.html.erb
<div class="container py-5">
  <h1 class="text-center">Edit your trip:</h1>
  <%= render "form", trip: @trip %>
</div>

app/views/trips/index.html.erb
<div class="container py-5 pb-3">
  <h2 class="text-center fw-bold">Your trips</h2>
    <div class="row">
      <% @trips.each do |trip| %>
        <%= link_to trip_path(trip), class: "card-cat-link" do %>
          <div class="col py-3">
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= trip.photo.url %>)">
              <%= trip.name %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="text-end my-3">
      <%= link_to "Create a new trip", new_trip_path, class: "btn btn-primary home-btn" %>
    </div>
</div>

app/views/trips/new.html.erb
<div class="container py-3 pb-5">
  <h2 class="text-center fw-bold pb-3">Create a trip</h2>
  <%= render "form", trip: @trip %>
</div>

app/views/trips/show.html.erb
<% if @trip.user == current_user %>
<div class="d-flex justify-content-center align-items-center text-center trip-show-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @trip.photo.key %>')">
    <h1 class="display-5 fw-bold text-white"><span class="highlight"><%= @trip.name %></span></h1>
</div>
<div class="container py-5">
  <div class="row">
    <% @trip.posts.sort_by(&:date).reverse.each do |post| %>
      <div class="col-3">
        <%= link_to post_path(post), class: "card-cat-link" do %>
          <div class="card mb-3 border-0 round-body ">
            <%= cl_image_tag post.cover_photo.key, class:"card-img-top round-top" %>
            <div class="card-body text-center">
              <p class="card-text small fw-bold text-black"><%= post.date.strftime("%e %b %Y") %></p>
              <h3 class="card-title pb-1 fw-bold text-black"><span class="highlight"><%= post.address.chomp[/^([^,])+/] %></span></h3>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-end align-items-center">
    <p><%= link_to "Edit this trip", edit_trip_path, class: "btn btn-outline-primary text-center me-3" %></p>
    <p><%= link_to "Delete this trip",  @trip, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger text-center me-3" %></p>
    <p><%= link_to "Back to all trips", trips_path, class: "btn btn-outline-success text-center" %></p>
  </div>
</div>
<% else %>
  <div class="explore-page">
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-12 col-sm-6">
          <div class="show-secret">
            <h2 class="text-center">Other traveller's trips are private 🤫</h2>
            <p><%= link_to "Browse your own", trips_path %> or <%= link_to "create a new one", new_trip_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>